"""change nullable column of pdm table

Revision ID: 036d7c7d65d3
Revises: e9913773fd0e
Create Date: 2024-08-14 11:48:13.131256

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '036d7c7d65d3'
down_revision = 'e9913773fd0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pdm', schema=None) as batch_op:
        batch_op.alter_column('ma_tim_dong_ho_pdm',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('transmitter',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('qn',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('q3',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('r',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('dia_chi',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pdm', schema=None) as batch_op:
        batch_op.alter_column('dia_chi',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('r',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('q3',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('qn',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('transmitter',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('ma_tim_dong_ho_pdm',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    # ### end Alembic commands ###
