"""add groupId column to dongho table

Revision ID: 303cd9595494
Revises: 78024b746e30
Create Date: 2024-10-10 10:18:04.796638

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '303cd9595494'
down_revision = '78024b746e30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dongho', schema=None) as batch_op:
        batch_op.add_column(sa.Column('group_id', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dongho', schema=None) as batch_op:
        batch_op.drop_column('group_id')

    # ### end Alembic commands ###
