"""change nullable column of pdm table

Revision ID: 55bcdc1462c3
Revises: 036d7c7d65d3
Create Date: 2024-08-14 11:52:29.781509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55bcdc1462c3'
down_revision = '036d7c7d65d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pdm', schema=None) as batch_op:
        batch_op.alter_column('dn',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pdm', schema=None) as batch_op:
        batch_op.alter_column('dn',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    # ### end Alembic commands ###
