"""change nullable column of pdm table

Revision ID: 62fba030fda7
Revises: 55bcdc1462c3
Create Date: 2024-08-14 11:52:54.441954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62fba030fda7'
down_revision = '55bcdc1462c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pdm', schema=None) as batch_op:
        batch_op.alter_column('ccx',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pdm', schema=None) as batch_op:
        batch_op.alter_column('ccx',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    # ### end Alembic commands ###
