"""change id of dongHo table

Revision ID: 713a9dc6edfc
Revises: c0b9f2e87cc8
Create Date: 2024-10-15 14:42:54.459186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '713a9dc6edfc'
down_revision = 'c0b9f2e87cc8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dongho',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.String(length=255), nullable=True),
    sa.Column('ten_dong_ho', sa.String(length=255), nullable=False),
    sa.Column('phuong_tien_do', sa.String(length=255), nullable=True),
    sa.Column('seri_chi_thi', sa.String(length=255), nullable=True),
    sa.Column('seri_sensor', sa.String(length=255), nullable=True),
    sa.Column('kieu_chi_thi', sa.String(length=255), nullable=True),
    sa.Column('kieu_sensor', sa.String(length=255), nullable=True),
    sa.Column('kieu_thiet_bi', sa.String(length=255), nullable=True),
    sa.Column('co_so_san_xuat', sa.String(length=255), nullable=True),
    sa.Column('so_tem', sa.String(length=255), nullable=True),
    sa.Column('nam_san_xuat', sa.Date(), nullable=True),
    sa.Column('dn', sa.String(length=255), nullable=True),
    sa.Column('d', sa.String(length=255), nullable=True),
    sa.Column('ccx', sa.String(length=255), nullable=True),
    sa.Column('q3', sa.String(length=255), nullable=True),
    sa.Column('r', sa.String(length=255), nullable=True),
    sa.Column('qn', sa.String(length=255), nullable=True),
    sa.Column('k_factor', sa.String(length=255), nullable=True),
    sa.Column('so_qd_pdm', sa.String(length=255), nullable=True),
    sa.Column('ten_khach_hang', sa.String(length=255), nullable=True),
    sa.Column('co_so_su_dung', sa.String(length=255), nullable=True),
    sa.Column('phuong_phap_thuc_hien', sa.String(length=255), nullable=True),
    sa.Column('chuan_thiet_bi_su_dung', sa.String(length=255), nullable=True),
    sa.Column('nguoi_kiem_dinh', sa.String(length=255), nullable=True),
    sa.Column('ngay_thuc_hien', sa.Date(), nullable=True),
    sa.Column('hieu_luc_bien_ban', sa.Date(), nullable=True),
    sa.Column('vi_tri', sa.String(length=255), nullable=True),
    sa.Column('nhiet_do', sa.String(length=255), nullable=True),
    sa.Column('do_am', sa.String(length=255), nullable=True),
    sa.Column('du_lieu_kiem_dinh', sa.Text(), nullable=True),
    sa.Column('so_giay_chung_nhan', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dongho')
    # ### end Alembic commands ###
