"""change name of implementer column to nguoi_kiem_dinh

Revision ID: 78024b746e30
Revises: a1ce438d6969
Create Date: 2024-09-25 15:53:21.036213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78024b746e30'
down_revision = 'a1ce438d6969'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dongho', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nguoi_kiem_dinh', sa.String(length=255), nullable=True))
        batch_op.drop_column('implementer')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dongho', schema=None) as batch_op:
        batch_op.add_column(sa.Column('implementer', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.drop_column('nguoi_kiem_dinh')

    # ### end Alembic commands ###
