"""change column table DongHo

Revision ID: 7dd3017e4272
Revises: e70385a6c521
Create Date: 2024-09-23 18:14:23.871274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7dd3017e4272'
down_revision = 'e70385a6c521'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dongho', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seri_number', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('phuong_tien_do', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('seri_chi_thi', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('seri_sensor', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('kieu_chi_thi', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('kieu_sensor', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('kieu_thiet_bi', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('co_so_san_xuat', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('so_tem', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('nam_san_xuat', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('k_factor', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('ten_khach_hang', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('co_so_su_dung', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('phuong_phap_thuc_hien', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('chuan_thiet_bi_su_dung', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('ngay_thuc_hien', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('vi_tri', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('nhiet_do', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('do_am', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('du_lieu_kieu_dinh', sa.Text(), nullable=True))
        batch_op.drop_column('kieuthietbi')
        batch_op.drop_column('kfactor')
        batch_op.drop_column('doam')
        batch_op.drop_column('ngaythuchien')
        batch_op.drop_column('kieuchithi')
        batch_op.drop_column('tenkhachhang')
        batch_op.drop_column('dulieukiemdinh')
        batch_op.drop_column('sotem')
        batch_op.drop_column('serinumber')
        batch_op.drop_column('namsanxuat')
        batch_op.drop_column('serisensor')
        batch_op.drop_column('phuongtiendo')
        batch_op.drop_column('phuongphapthuchien')
        batch_op.drop_column('kieusensor')
        batch_op.drop_column('serichithi')
        batch_op.drop_column('nhietdo')
        batch_op.drop_column('chuanthietbisudung')
        batch_op.drop_column('vitri')
        batch_op.drop_column('cososudung')
        batch_op.drop_column('cososanxuat')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dongho', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cososanxuat', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('cososudung', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('vitri', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('chuanthietbisudung', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('nhietdo', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('serichithi', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('kieusensor', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('phuongphapthuchien', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('phuongtiendo', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('serisensor', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('namsanxuat', sa.DATE(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('serinumber', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('sotem', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('dulieukiemdinh', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('tenkhachhang', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('kieuchithi', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('ngaythuchien', sa.DATE(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('doam', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('kfactor', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('kieuthietbi', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.drop_column('du_lieu_kieu_dinh')
        batch_op.drop_column('do_am')
        batch_op.drop_column('nhiet_do')
        batch_op.drop_column('vi_tri')
        batch_op.drop_column('ngay_thuc_hien')
        batch_op.drop_column('chuan_thiet_bi_su_dung')
        batch_op.drop_column('phuong_phap_thuc_hien')
        batch_op.drop_column('co_so_su_dung')
        batch_op.drop_column('ten_khach_hang')
        batch_op.drop_column('k_factor')
        batch_op.drop_column('nam_san_xuat')
        batch_op.drop_column('so_tem')
        batch_op.drop_column('co_so_san_xuat')
        batch_op.drop_column('kieu_thiet_bi')
        batch_op.drop_column('kieu_sensor')
        batch_op.drop_column('kieu_chi_thi')
        batch_op.drop_column('seri_sensor')
        batch_op.drop_column('seri_chi_thi')
        batch_op.drop_column('phuong_tien_do')
        batch_op.drop_column('seri_number')

    # ### end Alembic commands ###
