"""change nullable column of pdm table

Revision ID: a82daba81b80
Revises: f121a9287d2b
Create Date: 2024-08-14 11:54:07.348356

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a82daba81b80'
down_revision = 'f121a9287d2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pdm', schema=None) as batch_op:
        batch_op.alter_column('ngay_het_han',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pdm', schema=None) as batch_op:
        batch_op.alter_column('ngay_het_han',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)

    # ### end Alembic commands ###
