"""rm serial num column and add id and tendongho to dongho table

Revision ID: c0b9f2e87cc8
Revises: 303cd9595494
Create Date: 2024-10-14 15:40:39.420889

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c0b9f2e87cc8'
down_revision = '303cd9595494'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dongho', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('ten_dong_ho', sa.String(length=255), nullable=False))
        batch_op.drop_column('serial_number')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dongho', schema=None) as batch_op:
        batch_op.add_column(sa.Column('serial_number', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.drop_column('ten_dong_ho')
        batch_op.drop_column('id')

    # ### end Alembic commands ###
