"""add DongHo table

Revision ID: e70385a6c521
Revises: 3f770ca3bb98
Create Date: 2024-09-23 17:07:21.308505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e70385a6c521'
down_revision = '3f770ca3bb98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dongho',
    sa.Column('serinumber', sa.String(length=255), nullable=False),
    sa.Column('phuongtiendo', sa.String(length=255), nullable=True),
    sa.Column('serichithi', sa.String(length=255), nullable=True),
    sa.Column('serisensor', sa.String(length=255), nullable=True),
    sa.Column('kieuchithi', sa.String(length=255), nullable=True),
    sa.Column('kieusensor', sa.String(length=255), nullable=True),
    sa.Column('kieuthietbi', sa.String(length=255), nullable=True),
    sa.Column('cososanxuat', sa.String(length=255), nullable=True),
    sa.Column('sotem', sa.String(length=255), nullable=True),
    sa.Column('namsanxuat', sa.Date(), nullable=True),
    sa.Column('dn', sa.String(length=255), nullable=True),
    sa.Column('d', sa.String(length=255), nullable=True),
    sa.Column('ccx', sa.String(length=255), nullable=True),
    sa.Column('q3', sa.String(length=255), nullable=True),
    sa.Column('r', sa.String(length=255), nullable=True),
    sa.Column('qn', sa.String(length=255), nullable=True),
    sa.Column('kfactor', sa.String(length=255), nullable=True),
    sa.Column('so_qd_pdm', sa.String(length=255), nullable=True),
    sa.Column('tenkhachhang', sa.String(length=255), nullable=True),
    sa.Column('cososudung', sa.String(length=255), nullable=True),
    sa.Column('phuongphapthuchien', sa.String(length=255), nullable=True),
    sa.Column('chuanthietbisudung', sa.String(length=255), nullable=True),
    sa.Column('implementer', sa.String(length=255), nullable=True),
    sa.Column('ngaythuchien', sa.Date(), nullable=True),
    sa.Column('vitri', sa.String(length=255), nullable=True),
    sa.Column('nhietdo', sa.String(length=255), nullable=True),
    sa.Column('doam', sa.String(length=255), nullable=True),
    sa.Column('dulieukiemdinh', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('serinumber')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dongho')
    # ### end Alembic commands ###
