"""add anh_pdm col to pdm table

Revision ID: e9913773fd0e
Revises: f29486fd6e2c
Create Date: 2024-08-14 11:34:32.263049

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9913773fd0e'
down_revision = 'f29486fd6e2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pdm', schema=None) as batch_op:
        batch_op.add_column(sa.Column('anh_pdm', sa.String(length=255), nullable=True))
        batch_op.alter_column('ma_tim_dong_ho_pdm',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('ten_dong_ho',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('noi_san_xuat',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('dn',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('ccx',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('kieu_sensor',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('transmitter',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('qn',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('q3',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('r',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('don_vi_pdm',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('dia_chi',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('so_qd_pdm',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('ngay_qd_pdm',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               nullable=False)
        batch_op.alter_column('ngay_het_han',
               existing_type=sa.DATE(),
               type_=sa.DateTime(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pdm', schema=None) as batch_op:
        batch_op.alter_column('ngay_het_han',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               nullable=True)
        batch_op.alter_column('ngay_qd_pdm',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               nullable=True)
        batch_op.alter_column('so_qd_pdm',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('dia_chi',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('don_vi_pdm',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('r',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('q3',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('qn',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('transmitter',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('kieu_sensor',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('ccx',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('dn',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('noi_san_xuat',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('ten_dong_ho',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('ma_tim_dong_ho_pdm',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.drop_column('anh_pdm')

    # ### end Alembic commands ###
