"""change nullable column of pdm table

Revision ID: f121a9287d2b
Revises: 62fba030fda7
Create Date: 2024-08-14 11:53:43.596644

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f121a9287d2b'
down_revision = '62fba030fda7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pdm', schema=None) as batch_op:
        batch_op.alter_column('ngay_qd_pdm',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pdm', schema=None) as batch_op:
        batch_op.alter_column('ngay_qd_pdm',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)

    # ### end Alembic commands ###
