"""add pdm table

Revision ID: f29486fd6e2c
Revises: f25e493bcee1
Create Date: 2024-08-12 15:26:44.425231

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f29486fd6e2c'
down_revision = 'f25e493bcee1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pdm',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ma_tim_dong_ho_pdm', sa.String(length=255), nullable=False),
    sa.Column('ten_dong_ho', sa.String(length=255), nullable=False),
    sa.Column('noi_san_xuat', sa.String(length=255), nullable=False),
    sa.Column('dn', sa.String(length=255), nullable=False),
    sa.Column('ccx', sa.String(length=255), nullable=False),
    sa.Column('kieu_sensor', sa.String(length=255), nullable=False),
    sa.Column('transmitter', sa.String(length=255), nullable=False),
    sa.Column('qn', sa.String(length=255), nullable=False),
    sa.Column('q3', sa.String(length=255), nullable=False),
    sa.Column('r', sa.String(length=255), nullable=False),
    sa.Column('don_vi_pdm', sa.String(length=255), nullable=False),
    sa.Column('dia_chi', sa.String(length=255), nullable=False),
    sa.Column('so_qd_pdm', sa.String(length=255), nullable=False),
    sa.Column('ngay_qd_pdm', sa.DateTime(), nullable=False),
    sa.Column('ngay_het_han', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pdm')
    # ### end Alembic commands ###
