"""add noi_su_dung column to DongHo table

Revision ID: f5ff707d22b4
Revises: 713a9dc6edfc
Create Date: 2024-11-13 11:23:50.599078

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5ff707d22b4'
down_revision = '713a9dc6edfc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dongho', schema=None) as batch_op:
        batch_op.add_column(sa.Column('noi_su_dung', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dongho', schema=None) as batch_op:
        batch_op.drop_column('noi_su_dung')

    # ### end Alembic commands ###
